name: WhatsApp Bot Daily

on:
  schedule:
    - cron: '5 3 * * *' # 23:10 da noite no Brasil (UTC-3 = 02:10 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run WhatsApp bot
        env:
          ULTRAMSG_INSTANCE_ID: ${{ secrets.ULTRAMSG_INSTANCE_ID }}
          ULTRAMSG_TOKEN: ${{ secrets.ULTRAMSG_TOKEN }}
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
        run: python bot_whatsapp_automatico.py
